In [1]:
import pandas as pd

In [2]:
posts = pd.read_csv('blogset-br.csv', header=None)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
authors = pd.read_csv('4300Answers.csv')

In [4]:
authors.head()

,Timestamp,AuthorID,Sobre qual(is) tópico(s) você mais escreve?,Utiliza outra rede social?,Qual sua idade?,Qual seu sexo?,Qual sua atividade profissional?,Qual o endereço do seu blogspot?,Onde você mora?,Código Único,Há quanto tempo você mantém esse blog?,Qual o período de atualização do blog?,Costuma deixar comentários nos blogs que segue?,Com relação a autoria do conteúdo de seu blog:,Quantidade média de acessos do seu blog por mês?,Nivel de Escolaridade,Gostaria que seu blog fosse publicado na lista deste estudo?
0,28-Mar-2012,08741884562446510660,"Tecnologia, Viagens","Twitter, Facebook, Orkut, Flickr, Linkedin",30 à 40 anos,Masculino,Professor,http://lkwives.blogspot.com.br/,Porto Alegre,08741884562446510660,entre 3 e 4 anos,mensalmente,"Sim, raramente",NaN,NaN,NaN,NaN
1,29-Mar-2012,07057956474529920239,"Artes, Filosofia, Literatura / Livros, Polític...",NaN,40 à 60 anos,Masculino,Jornalista e sociólogo (agora também formado e...,www.juliprates.blogspot.com,SANTIAGO/RS/BRASIL,07057956474529920239,mais de 4 anos,diariamente,Não costumo deixar comentários,NaN,NaN,NaN,NaN
2,29-Mar-2012,11807897332463595720,"Filosofia, Tecnologia","Facebook, Linkedin",19 à 25 anos,Masculino,Consultor de Software,http://configuracaominima.blogspot.com,"Porto Alegre, RS, Brasil",11807897332463595720,mais de 4 anos,raramente,Não costumo deixar comentários,NaN,NaN,NaN,NaN
3,29-Mar-2012,05737856882009129069,"Política, Saúde, Tecnologia, VÍDEOS. JÁ PUBLIC...",Facebook,mais de 60 anos,Masculino,MÉDICO,www.sdcidad.blogspot.com,"FEIRA DE SANTANA,BAHIA,BRASIL",05737856882009129069,entre 1 e 2 anos,diariamente,"Sim, raramente",NaN,NaN,NaN,NaN
4,30-Mar-2012,04650502123448146932,"Futebol, Política","Twitter, Facebook, Orkut, Linkedin",40 à 60 anos,Masculino,jornalista,http://blogentrelinhas.blogspot.com.br/,"são paulo, SP, Brasil",04650502123448146932,mais de 4 anos,raramente,"Sim, raramente",NaN,NaN,NaN,NaN

In [6]:
authors.columns

Index(['Timestamp', 'AuthorID', 'Sobre qual(is) tópico(s) você mais escreve?',
       'Utiliza outra rede social?', 'Qual sua idade?', 'Qual seu sexo?',
       'Qual sua atividade profissional?', 'Qual o endereço do seu blogspot?',
       'Onde você mora?', 'Código Único',
       'Há quanto tempo você mantém esse blog?',
       'Qual o período de atualização do blog?',
       'Costuma deixar comentários nos blogs que segue?',
       'Com relação a autoria do conteúdo de seu blog:',
       'Quantidade média de acessos do seu blog por mês?',
       'Nivel de Escolaridade',
       'Gostaria que seu blog fosse publicado na lista deste estudo?'],
      dtype='object')

In [5]:
authors["Código Único"].value_counts()

07557338144870840266    7
05716911388205627486    6
07362894277513996308    5
03882246600537606379    4
12924125294519710268    4
00953331853847272494    4
15319374435083808878    3
06662290017182383801    3
01888226374213432574    3
00371646788282005825    3
16529549447616554966    3
14651731069478461197    3
04749576487033568460    3
16284380357060198508    3
15694484356048829259    3
11771186187669627206    2
00350292607655201471    2
02247723283971164894    2
11191767810204769271    2
11172805455134389700    2
07065018946245747319    2
08863187599250706659    2
02812321827943081766    2
05032690517515543008    2
00321492104334239449    2
05194966574202868541    2
07795765002433519460    2
12271968860205342859    2
01244927597010331486    2
09839509390439857759    2
                       ..
16510160622093241510    1
11325271785898457865    1
16603748008555351341    1
17900493214415159181    1
10058982946935643204    1
17703747861575992602    1
06246123458959851313    1
10685723324268024058    1
05221753093049208109    1
10487549844453918026    1
09627946022039249197    1
04679522875728006979    1
05916040845402454172    1
16865278807829285015    1
14708561423489986270    1
02710801120750037668    1
02377264651618319209    1
11656753628035168171    1
14150257503707629622    1
11731692826904402401    1
00831723561918780820    1
00761854381979826117    1
01190577182378282893    1
03641573384345782575    1
07728783192319102730    1
02183135309441783719    1
09204304896278801642    1
01634019855200946997    1
14235339815764007321    1
14215468809924841108    1
Name: Código Único, Length: 4203, dtype: int64

In [7]:
posts.head()

,0,1,2,3,4,5,6,7,8
0,4513095612773714447,1000016902259367892,2012-01-27T13:30:00-02:00,Ombré nails como fazer,\n,01861978533047910632,Daniela,1,NaN
1,4402618022359447709,1000016902259367892,2011-07-25T21:43:00-03:00,RISQUÉ - COLOR,SÃAAAO MUITOO LINDOS AMEEI OOO MIRAGEM AZUL *-*,01861978533047910632,Daniela,0,NaN
2,4903861431859076038,1000016902259367892,2011-10-06T23:39:00-03:00,Risque Dogs,A Nova coleção da Risqué veeeeio ANIMAL hehe c...,01861978533047910632,Daniela,3,NaN
3,5936720117277385447,1000016902259367892,2011-07-25T21:46:00-03:00,Risqué coleção nova da Penelope,esmaltes,01861978533047910632,Daniela,0,NaN
4,9035220881064614540,1000016902259367892,2011-05-04T00:09:00-03:00,Coleção 2011 MOHDA INVERNO,A MOHDA nesse inverno enta trazendo para nos v...,01861978533047910632,Daniela,0,NaN

In [8]:
authors[authors['Código Único']== '07557338144870840266']

,Timestamp,AuthorID,Sobre qual(is) tópico(s) você mais escreve?,Utiliza outra rede social?,Qual sua idade?,Qual seu sexo?,Qual sua atividade profissional?,Qual o endereço do seu blogspot?,Onde você mora?,Código Único,Há quanto tempo você mantém esse blog?,Qual o período de atualização do blog?,Costuma deixar comentários nos blogs que segue?,Com relação a autoria do conteúdo de seu blog:,Quantidade média de acessos do seu blog por mês?,Nivel de Escolaridade,Gostaria que seu blog fosse publicado na lista deste estudo?
813,18-Apr-2012,07557338144870840266,"Amizade, Cinema, Educação, Filosofia, Literatu...","Twitter, Wordpress, Facebook, Orkut",40 à 60 anos,Masculino,Escritor,http://e-bibliasevangelicas.blogspot.com.br/ -...,São José dos Campos - SP,07557338144870840266,entre 3 e 4 anos,3 vezes por semana,Não costumo deixar comentários,NaN,NaN,NaN,NaN
815,18-Apr-2012,07557338144870840266,"Amizade, Cinema, Educação, Filosofia, Literatu...","Twitter, Wordpress, Facebook, Orkut",40 à 60 anos,Masculino,Escritor,http://e-bibliasevangelicas.blogspot.com.br/ -...,São José dos Campos - SP,07557338144870840266,entre 3 e 4 anos,3 vezes por semana,Não costumo deixar comentários,NaN,NaN,NaN,NaN
816,18-Apr-2012,07557338144870840266,"Amizade, Cinema, Educação, Filosofia, Literatu...","Twitter, Wordpress, Facebook, Orkut",40 à 60 anos,Masculino,Escritor,http://e-bibliasevangelicas.blogspot.com.br/ -...,São José dos Campos - SP,07557338144870840266,entre 3 e 4 anos,3 vezes por semana,Não costumo deixar comentários,NaN,NaN,NaN,NaN
817,18-Apr-2012,07557338144870840266,"Amizade, Cinema, Educação, Filosofia, Literatu...","Twitter, Wordpress, Facebook, Orkut",40 à 60 anos,Masculino,Escritor,http://e-bibliasevangelicas.blogspot.com.br/ -...,São José dos Campos - SP,07557338144870840266,entre 3 e 4 anos,3 vezes por semana,Não costumo deixar comentários,NaN,NaN,NaN,NaN
819,18-Apr-2012,07557338144870840266,"Amizade, Cinema, Educação, Filosofia, Literatu...","Twitter, Wordpress, Facebook, Orkut",40 à 60 anos,Masculino,Escritor,http://e-bibliasevangelicas.blogspot.com.br/ -...,São José dos Campos - SP,07557338144870840266,entre 3 e 4 anos,3 vezes por semana,Não costumo deixar comentários,NaN,NaN,NaN,NaN
821,18-Apr-2012,07557338144870840266,"Amizade, Cinema, Educação, Filosofia, Literatu...","Twitter, Wordpress, Facebook, Orkut",40 à 60 anos,Masculino,Escritor,http://e-bibliasevangelicas.blogspot.com.br/ -...,São José dos Campos - SP,07557338144870840266,entre 3 e 4 anos,3 vezes por semana,Não costumo deixar comentários,NaN,NaN,NaN,NaN
822,18-Apr-2012,07557338144870840266,"Amizade, Cinema, Educação, Filosofia, Literatu...","Twitter, Wordpress, Facebook, Orkut",40 à 60 anos,Masculino,Escritor,http://e-bibliasevangelicas.blogspot.com.br/ -...,São José dos Campos - SP,07557338144870840266,entre 3 e 4 anos,3 vezes por semana,Não costumo deixar comentários,NaN,NaN,NaN,NaN

In [17]:
ids_authors = authors['AuthorID'].tolist()

In [11]:
posts.shape

(7477854, 9)

In [19]:
texts_by_author = []
for id in ids_authors:
    df_author = posts[posts[5]==id]
    texts = df_author[4].tolist()
    complete_text = " ".join(texts)
    texts_by_author.append(complete_text)

In [20]:
len(texts_by_author)

4331

In [21]:
authors["Texts"] = texts_by_author

In [22]:
df = authors.drop(columns=['Timestamp', 'Sobre qual(is) tópico(s) você mais escreve?', 'Utiliza outra rede social?', 'Qual sua atividade profissional?', 'Qual o endereço do seu blogspot?',
'Onde você mora?', 'Código Único',
       'Há quanto tempo você mantém esse blog?',
       'Qual o período de atualização do blog?',
       'Costuma deixar comentários nos blogs que segue?',
       'Com relação a autoria do conteúdo de seu blog:',
       'Quantidade média de acessos do seu blog por mês?',
       'Nivel de Escolaridade', "Gostaria que seu blog fosse publicado na lista deste estudo?"])

In [23]:
import numpy as np

In [24]:
df['Qual sua idade?'] = df['Qual sua idade?'].replace('', np.nan)
df['Qual seu sexo?'] = df['Qual seu sexo?'].replace('', np.nan)
df['Texts'] = df['Texts'].replace('', np.nan)

In [25]:
df[df['Qual sua idade?'].isna()]

Empty DataFrame
Columns: [AuthorID, Qual sua idade?, Qual seu sexo?, Texts]
Index: []

In [26]:
df[df['Qual seu sexo?'].isna()]

Empty DataFrame
Columns: [AuthorID, Qual sua idade?, Qual seu sexo?, Texts]
Index: []

In [27]:
df[df['Texts'].isna()]

                  AuthorID  Qual sua idade? Qual seu sexo? Texts
0     08741884562446510660     30 à 40 anos      Masculino   NaN
1     07057956474529920239     40 à 60 anos      Masculino   NaN
5     18293665820530618159     40 à 60 anos      Masculino   NaN
6     05755156476401117693     26 à 30 anos      Masculino   NaN
8     04385119848391824862     10 à 18 anos      Masculino   NaN
9     17650645083714029617     10 à 18 anos      Masculino   NaN
13    01045238316109618735     40 à 60 anos      Masculino   NaN
15    11913273967319115493     30 à 40 anos       Feminino   NaN
16    16353194221938449397     30 à 40 anos       Feminino   NaN
35    02068187732016991417     30 à 40 anos       Feminino   NaN
36    14137238820238584896     30 à 40 anos      Masculino   NaN
37    11186051674793350381     40 à 60 anos      Masculino   NaN
39    11485856768120872641     19 à 25 anos       Feminino   NaN
43    01831328123759710020     30 à 40 anos       Feminino   NaN
44    00054611270985895742     40 à 60 anos       Feminino   NaN
45    06006185604020806793     26 à 30 anos      Masculino   NaN
49    14603945652082130851     30 à 40 anos       Feminino   NaN
50    15661639338745383347     10 à 18 anos      Masculino   NaN
51    09204304896278801642     40 à 60 anos       Feminino   NaN
54    14939953365934870597     19 à 25 anos      Masculino   NaN
56    15168460049313307009     19 à 25 anos       Feminino   NaN
58    15168460049313307009     19 à 25 anos       Feminino   NaN
65    05316095134917326418     40 à 60 anos      Masculino   NaN
66    03321489268868339671     30 à 40 anos      Masculino   NaN
69    01316913573572493872     30 à 40 anos       Feminino   NaN
70    07699114235482521560     30 à 40 anos       Feminino   NaN
71    14989190910421316913     26 à 30 anos       Feminino   NaN
75    04708187989882546232     30 à 40 anos      Masculino   NaN
76    07787109783208604253     26 à 30 anos       Feminino   NaN
77    08442420554589108404     40 à 60 anos       Feminino   NaN
...                    ...              ...            ...   ...
4245  05243983108387288930     10 à 18 anos      Masculino   NaN
4248  04668082318483126364     26 à 30 anos      Masculino   NaN
4251  01722785619075218138     40 à 60 anos      Masculino   NaN
4254  14367235567564212630     19 à 25 anos       Feminino   NaN
4259  06122817141263393121     26 à 30 anos       Feminino   NaN
4260  06499094968138152396  mais de 60 anos       Feminino   NaN
4267  10578081236128815208     40 à 60 anos      Masculino   NaN
4268  08050669092012039216     10 à 18 anos       Feminino   NaN
4270  05088947395792327699     19 à 25 anos      Masculino   NaN
4274  14116770441730642880     26 à 30 anos      Masculino   NaN
4277  11959595167057895026     30 à 40 anos       Feminino   NaN
4279  10722320032355450997     10 à 18 anos       Feminino   NaN
4280  15805279337057860558     26 à 30 anos       Feminino   NaN
4283  06052262646280830463     26 à 30 anos       Feminino   NaN
4285  14813205319484696490     40 à 60 anos       Feminino   NaN
4286  11219786218131708600     26 à 30 anos      Masculino   NaN
4288  12409178876741750274     19 à 25 anos       Feminino   NaN
4289  08671896954475692179     40 à 60 anos      Masculino   NaN
4293  16753543116454959160     40 à 60 anos       Feminino   NaN
4298  06374083617469589996     10 à 18 anos      Masculino   NaN
4300  07737667363688338849     40 à 60 anos      Masculino   NaN
4301  18402525079828616085     40 à 60 anos       Feminino   NaN
4303  14779259461032120117     30 à 40 anos       Feminino   NaN
4307  16951834240681152727     30 à 40 anos      Masculino   NaN
4309  07815516586417123115     40 à 60 anos      Masculino   NaN
4312  17150793325387229078     40 à 60 anos       Feminino   NaN
4318  05099667804478905629     19 à 25 anos      Masculino   NaN
4319  06038484621762765921     40 à 60 anos      Masculino   NaN
4324  16973794885690227724     10 à 18 anos      Masculino   NaN
4326  04978720838903904441     26 à 30 anos      Masculino   NaN

[1727 rows x 4 columns]

In [14]:
df.shape

(4331, 4)

In [28]:
df.dropna(subset=['Qual seu sexo?', 'Qual sua idade?', 'Texts'], inplace=True)

In [29]:
df.shape

(2604, 4)

In [30]:
df['Qual seu sexo?'].value_counts()

Masculino    1564
Feminino     1040
Name: Qual seu sexo?, dtype: int64

In [31]:
df['Qual sua idade?'].value_counts()

40 à 60 anos       777
30 à 40 anos       672
19 à 25 anos       441
26 à 30 anos       349
10 à 18 anos       228
mais de 60 anos    137
Name: Qual sua idade?, dtype: int64

In [32]:
def getAgeGroups(text):
    if text == '10 à 18 anos' or text == '19 à 25 anos':
        return 0
    elif text == '26 à 30 anos' or text == '30 à 40 anos':
        return 1
    else:
        return 2

In [33]:
df['AgeClass'] = df['Qual sua idade?'].apply(getAgeGroups)

In [34]:
df['AgeClass'].value_counts()

1    1021
2     914
0     669
Name: AgeClass, dtype: int64

In [35]:
df.drop_duplicates()

,AuthorID,Qual sua idade?,Qual seu sexo?,Texts,AgeClass
2,11807897332463595720,19 à 25 anos,Masculino,O designer inglês Graham Smith criou uma série...,0
3,05737856882009129069,mais de 60 anos,Masculino,\n\n\n\n\n\n\n\n\n\nA sonda espacial Soho da N...,2
4,04650502123448146932,40 à 60 anos,Masculino,O pessoal da ultra-direita anda mais animado q...,2
7,02534662484984494401,40 à 60 anos,Masculino,\n\nColaborou Vandeli - 26/12/1 12:25h\n\n\nA ...,2
10,08353750961625391396,30 à 40 anos,Masculino,\n\n\n\n\nA Sra. Tweedy (Miranda Richardson/Ná...,1
11,04765527299993287474,30 à 40 anos,Feminino,Quem não sonha com uma casa toda organizada? C...,1
12,13164559677688732625,26 à 30 anos,Masculino,"Sim, estamos chegando no dia dos namorados. Co...",1
14,09835968977334621360,19 à 25 anos,Feminino,"A noite, Quimera que devora,\nFaz ruir o sono,...",0
17,08254536594356401073,30 à 40 anos,Masculino,\n\n\n\n\n\n\nAlexandre\nestava caminhando pel...,1
18,12563981285270814753,30 à 40 anos,Feminino,\nOs últimos anos foram de muitas mudanças em ...,1
19,00863286488423631590,19 à 25 anos,Masculino,\n\n\noriginal\n\n\nTodo mundo.\nDesespero\nTo...,0
20,16032334193005114000,mais de 60 anos,Masculino,\n\n \n\n \n\n\n\nDilma e o PT já podem arruma...,2
21,12152962690069479736,30 à 40 anos,Feminino,E acontece o mesmo quando estou alegre ou tris...,1
22,01388262066608326377,10 à 18 anos,Masculino,\n\nPra vocês que acharam que eu não iria volt...,0
23,02056195025990715890,40 à 60 anos,Feminino,\n\n\n\n\n\n\n\n\n\n\nHá solidão na casa sem b...,2
24,01537485251623482301,40 à 60 anos,Masculino,"Do livro A arte de questionar, de A.C. Graylin...",2
25,00445483161028871152,10 à 18 anos,Feminino,"""meu problema é a preguiça, não consigo nem go...",0
26,01596617235776092416,19 à 25 anos,Masculino,"Tudo que é perfeito demais gera inveja, rivali...",0
27,11808710045704169055,26 à 30 anos,Feminino,"\n""Gabe voltou-se para mim e falou na voz rouc...",1
28,08987705586764729187,mais de 60 anos,Feminino,TUDO O QUE TENHO LEVO COMIGO Exposição mostra ...,2
29,14903723407087991529,19 à 25 anos,Feminino,"\nAmaaados, eu ainda vivo! E trouxe uma super-...",0
30,03307923397404217789,19 à 25 anos,Masculino,"Hello, menininhos e menininhas. Após uma breve...",0
31,18041834015199611108,40 à 60 anos,Masculino,<!--[if gte mso 9]>\n \n Normal\n 0\n \n \...,2
32,11209737711648527795,40 à 60 anos,Masculino,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nA quantidade...,2
33,15219902367765250276,40 à 60 anos,Feminino,".\neu sei que não pode, que não dá, que tem al...",2
34,02079675629604968928,40 à 60 anos,Feminino,\n\n\n\n\n\n&nbsp;Olá amigos\n\n\n\n&nbsp;e am...,2
38,08595206817257211040,26 à 30 anos,Masculino,\n\n\nNo meio do caos surge tímido mas ao mesm...,1
40,15474902178889737589,10 à 18 anos,Masculino,\n\n\n\n\n\n\nCréditos:&nbsp;[rc-3d]\n\n\n\n\n...,0
41,10821588439927024075,40 à 60 anos,Feminino,"Bom dia,saudades desse pedacinho esquecido com...",2
42,10973882065913973679,30 à 40 anos,Masculino,"\n\n\n\n\n\n\nO fato de nunca ter trabalhado, ...",1
...,...,...,...,...,...
4281,01824231283642451863,40 à 60 anos,Feminino,Já falei algumas vezes aqui que fiz o Decola -...,2
4282,02311725187557242382,10 à 18 anos,Masculino,\nNa noite desta terça-feira &nbsp;(16-05) por...,0
4284,01518358722785590008,10 à 18 anos,Masculino,p { margin-bottom: 0.25cm; line-height: 120%; ...,0
4287,15329738369455732989,26 à 30 anos,Masculino,\n\n\nA Mini Miss Brasil\nUniverse Glan 2017 G...,1
4290,10461459688502865805,mais de 60 anos,Masculino,\n\n\n\nJosé Carlos Bolognese\n\n\nReflexões e...,2
4291,18246454609006869174,mais de 60 anos,Masculino,<!--[if gte mso 9]>\n \n \n \n \n<![endif]--...,2
4292,05060986556589341228,40 à 60 anos,Masculino,\nO presidente da Câmara de Vereadores de São ...,2
4294,09672563057036685819,19 à 25 anos,Masculino,A proporção áurea é uma regra matemática que p...,0
4295,03110320621771903904,30 à 40 anos,Masculino,\nLembram do Hang Loose Pro\nContest que coloc...,1
4296,06758223225700270740,40 à 60 anos,Feminino,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nVocê é o criad...,2
4297,10544620546238483538,40 à 60 anos,Masculino,"A Secretaria da Educação do Estado realiza, de...",2
4299,14355755310092013627,30 à 40 anos,Masculino,"\nSenhor,&nbsp;Admito&nbsp;minha dependência d...",1
4302,14360433044584583226,40 à 60 anos,Masculino,----- Mensagem encaminhada ----- De: Mu...,2
4304,03081201182991378616,40 à 60 anos,Masculino,\n\n\nTribunal de Contas autoriza apenas a tra...,2
4306,13007750798807740397,30 à 40 anos,Feminino,Em edição... \n\nJuliano escondendo os olhos a...,1
4308,11081441940649993163,10 à 18 anos,Masculino,\n\n\nSentido Bairro Centro: Estrada da Ceasa ...,0
4310,17489956330752044015,30 à 40 anos,Masculino,\n\n\nO gerente Carlos Morais cantando na fest...,1
4313,11610758260602595106,30 à 40 anos,Masculino,\n\nSEGUNDA-FEIRA\n\n\n\n05:00 Futuração – Açã...,1
4314,00467763492185158918,40 à 60 anos,Masculino,CONHEÇA MAIS SOBRE MANTRAS\nA palavra&nbsp;man...,2
4315,00454832946656715753,40 à 60 anos,Masculino,\n\nÉ gratificante ver um sorriso de um molequ...,2
4316,00321492104334239449,26 à 30 anos,Masculino,\n\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Deus ...,1
4320,13791938551837545708,30 à 40 anos,Masculino,"\n\n\nPor do sol visto do Bairro Bela Vista, e...",1
4321,12917157958581588222,19 à 25 anos,Masculino,"Se você sempre sonhou, assim como eu, em ser u...",0
4322,14016369818096794862,mais de 60 anos,Masculino,\n\n\n\n\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...,2
4323,10974042696539616307,26 à 30 anos,Masculino,&nbsp;&nbsp;&nbsp;&nbsp; Está disponível no Bl...,1
4325,09072434411192524298,10 à 18 anos,Masculino,\n\n \n\n \n\n \n\n \n\n \n\n\nNo dia 30 de No...,0
4327,16968395029423562069,19 à 25 anos,Masculino,\n\nMinistério da Agricultura do Brasil lançou...,0
4328,10142366745621401477,30 à 40 anos,Masculino,De acordo com pesquisa do Ministério da Justiç...,1
4329,15896847799633812396,30 à 40 anos,Masculino,\n\nMagnaldo Fernandes - Investigado\n\n\nDesd...,1
4330,06114700697103253208,40 à 60 anos,Feminino,\n<!--\n /* Font Definitions */\n@font-face\n ...,2

In [36]:
df.to_csv(("/home/alice/Pesquisa/tcc-v2/blogset-br/blogset-duplicate.csv"), index = False, header=True)

In [37]:
df_without_duplicates = df.drop_duplicates()

In [38]:
df_without_duplicates.to_csv(("/home/alice/Pesquisa/tcc-v2/blogset-br/blogset-without-duplicate.csv"), index = False, header=True)